spaceninjaserver/SpaceNinjaServer

src/services/saveLoadoutService.ts
This was causing unequipping weapons to fail again due to newer mongoose version.
=> fix: using ILoadoutConfigClient to write to database

src/controllers/api/hubInstancesController.ts
Makes the game think there's only 1 HUB instance so it won't ask us to pick one.
=> improve: skip HUB instance selection

static/fixed_responses/allShipFeatures.json
Needed to unlock Melee arcane & exilus slots.
=> fix: allShipFeatures not containing ArsenalMeleeFeatureItem

static/fixed_responses/allShipDecorations.json
This is the only orbiter decoration that does not start with `/Lotus/Types/Items/ShipDecos/`.
=> fix: missing note beacon in allShipDecorations

static/webui/script.js
changed modular weapon in webui from displaying "/Lotus/Weapons/Ostron/Melee/LotusModularWeapon" to "Zaw", it was too long and caused misalignment of texts and boxes
Before: 
After:
=> improve(webui): Zaw display label

static/fixed_responses/worldState.json
For some reason the DLL's `fallback_language` setting doesn't get picked up by this LanguageCode logic, so I've added the "Msg" field to serve as a fallback, and updated the remaining strings to be appropriately localised.
=> fix: not seeing any news in orbiter

.github/workflows/build.yml
Just to ensure we don't hit any edge cases.
=> improve: use all supported nodejs versions in workflow

package-lock.json, package.json
The latest version of RivenParser.js fixes some issues like erroring on rivens without a curses array.
=> chore: update warframe-riven-info

src/controllers/api/loginController.ts, src/controllers/dynamic/worldStateController.ts, src/routes/cache.ts
Newer versions of the DLL (>=0.6.0) can determine the client version and will tell the server via query parameters on these relevant requests. The server of course still needs to have a copy of the relevant H.Cache.bin file.
=> feat: respect client-supplied version information

docker-entrypoint.sh
The current `docker-entrypoint.sh` will write all numeric and boolean environment variables to `config.json` as strings, which will make most configurations invalid.
This Pull Request attempts to read the parameter in JSON format first. If it cannot be parsed, it is considered a string.
before
```json
{
"logger": {
"files": true,
"level": "trace",
"__valid_levels": "fatal, error, warn, info, http, debug, trace"
},
"universalPolarityEverywhere": "true",
"unlockAllShipFeatures": "false",
"httpsPort": "443",
"spoofMasteryRank": "-1",
"unlockAllShipDecorations": "false",
"skipStoryModeChoice": "false",
"autoCreateAccount": "true",
"httpPort": "80",
"skipAllDialogue": "false",
"unlockAllSkins": "false",
"completeAllQuests": "false",
"unlockAllFlavourItems": "false",
"mongodbUrl": …
```
=> Fix environment to config.json parser

src/controllers/api/purchaseController.ts, src/helpers/purchaseHelpers.ts
We typically don't 'validate' requests. In this case, this also results in some fields of the request being lost as they are not handled in the validate/parse function.
=> fix: inconsistent handling of purchase request

src/controllers/api/syndicateStandingBonusController.ts, src/routes/api.ts
Closes #535. Currently doesn't consider standing limits so you can end up with extra standing.
=> feat: implement syndicateStandingBonus endpoint

src/controllers/api/loginController.ts, src/controllers/dynamic/worldStateController.ts, src/routes/cache.ts, src/services/buildConfigService.ts
Previously, buildConfig.json was loaded from build/static/data while cache files were loaded from static/data. Now all files are loaded from static/data and there is no build/static/data folder anymore.
=> fix: consistenly use static/data for 'npm run build'

src/controllers/api/upgradesController.ts
The client assumes the request is always successful. InventoryChanges does need to be present but it seems the actual data in it doesn't matter, and what we were sending was gibberish anyway.
=> chore: simplify upgradesController

src/models/inventoryModels/inventoryModel.ts, src/types/inventoryTypes/inventoryTypes.ts
it is possible to e.g. only have 2/3 crew members active, then one of the slots is simply absent.
=> fix: make crew member slots optional

static/webui/index.html, static/webui/script.js
Adds 2 new buttons in the bulk actions container
1. to make every owned warframe max rank
2. to make every owned weapon max rank
also made the lists have a max width so the page doesnt need to be scrolled down all the way to see the buttons
=> feat(webui): add "max rank all warframes" & "max rank all weapons"

src/controllers/api/syndicateSacrificeController.ts
This actually fixes #392 as the missionInventoryUpdate logic regarding this seems to be correct.
=> fix: syndicate sacrifice doesn't persist new title

src/services/purchaseService.ts, src/types/purchaseTypes.ts
Closes #738, as otherwise the rotation is actually already handled by the client. We just need to use the ItemId it gives us.
=> fix: identify correct offer for when teshin has 2 kuva offers up

src/controllers/api/artifactsController.ts
=> fix: remove legendary core from inventory when it was used

UPDATE AND START SERVER.bat
It's possible one might acquire a lot of dead references from continually updating the server, so this will automatically prune them when synchronising with the git remote.
=> fix: automatically prune references that no longer exist remotely

src/controllers/api/rerollRandomModController.ts
=> fix: exclude riven buffs from being a curse

src/controllers/api/inventoryController.ts, src/controllers/api/missionInventoryUpdateController.ts, src/types/inventoryTypes/inventoryTypes.ts
temp fix for completeAllQuests: you won't be able to start a new quest with the config option enabled.
This will be changed in the future by making the feature an account based web-ui option.
closes #856 #855
=> fix: aborting Mission and completeAllQuests config
