spaceninjaserver/SpaceNinjaServer

src/app.ts
src/controllers/api/deleteSessionController.ts
src/controllers/api/genericUpdateController.ts
src/controllers/api/rerollRandomModController.ts
src/controllers/stats/uploadController.ts
src/routes/api.ts
src/routes/stats.ts

and fix a few errors from last pr

Add Reroll Random and Stats upload

---

src/services/mongoService.ts

Warn user that .env file is missing

Better error message when .env file is missing

---

package-lock.json
package.json

This reverts commit 6c77e8dcfcb7833dbc24da06f49bb35d14862fcc.

Revert "Bump mongoose from 7.4.1 to 7.6.3 (#73)"

---

.env.example
.gitignore
config.json
package-lock.json
package.json
src/app.ts
src/controllers/api/findSessionsController.ts
src/controllers/api/getCreditsController.ts
src/controllers/api/hostSessionController.ts
src/controllers/api/joinSessionController.ts
src/controllers/api/loginController.ts
src/controllers/api/rerollRandomModController.ts
src/controllers/api/saveLoadout.ts
src/controllers/api/setBootLocationController.ts
src/controllers/api/updateSessionController.ts
src/helpers/general.ts
src/index.ts
src/managers/sessionManager.ts
src/middleware/middleware.ts
src/middleware/morgenMiddleware.ts
src/services/inventoryService.ts
src/services/missionInventoryUpdateService .ts
src/services/mongoService.ts
src/services/purchaseService.ts
src/services/saveLoadoutService.ts
src/types/purchaseTypes.ts
src/utils/logger.ts

Log functions have the following format: logger.level(string, object) - object should have a key that holds the object like { info: object }
available levels are:
logger.*
fatal,
error,
warn,
info,
http,
debug,
trace

Improved logging using winston

---

src/middleware/morgenMiddleware.ts

removed whitespace/newline from http logging level

logging: formatting

---

src/types/personalRoomsTypes.ts

fixed missing import of IPlacedDecosDatabase

fix: personalRoomsTypes.ts missing import

---

src/controllers/api/updateThemeController.ts
src/routes/api.ts
src/services/inventoryService.ts
src/types/requestTypes.ts

saves UI customization (theme, background, sounds)

feat: theme saving

---

src/controllers/api/inventoryController.ts

This makes these values consistent with the values in getCreditsController, so they appear "correctly" right upon login.

Also apply infiniteResources on inventoryController response

---

src/controllers/api/getGuildController.ts
src/routes/api.ts

This is needed for login to succeed with certain inventories.

Implement /api/getGuild.php

---

src/controllers/api/genericUpdateController.ts

So we don't have to see this shit upon every login

feat: Process generic updates

---

.github/workflows/prettier.yml
src/controllers/api/genericUpdateController.ts
static/fixed_responses/aggregateSessions.json

- Changed the trigger to push so it works with forks.
- Added write permission which is now needed to commit.
- Updated node version to 20 to match package.json.

Fix prettier workflow

---

src/types/shipTypes.ts

improve: IShip

---

src/controllers/api/upgradesController.ts
src/routes/api.ts
src/services/inventoryService.ts
src/types/inventoryTypes/inventoryTypes.ts
src/types/requestTypes.ts

#161 to be able to purchase those items.

feat: potatoes & exilus adapters

---

static/fixed_responses/allQuestKeys.json

For "Whispers In The Walls" and whatever else was missing. Just copied every quest from the inventory on my personal account which has every quest completed.

feat: Update allQuestKeys.json

---

src/controllers/api/setBootLocationController.ts
src/models/personalRoomsModel.ts
src/types/personalRoomsTypes.ts
src/types/shipTypes.ts

feat: persist boot location

---

config.json
static/fixed_responses/worldState.json

matchmakingBuildId was not updated because I was unable to find the new one. It may be server-sided. The game didn't complain about it.

chore: update 35.5.11

---

src/controllers/api/inventoryController.ts

This will also allow arcane adapters to be purchased in the market

feat: unlock Steel Path with unlockAllMissions

---

src/controllers/custom/getItemListsController.ts
src/services/inventoryService.ts
static/webui/index.html
static/webui/script.js

improve(webui): fix add weapon, improve handling of unknown items, maintain scroll position

---

src/controllers/stats/viewController.ts
src/services/inventoryService.ts

feat: implement XPInfo

---

src/controllers/api/upgradesController.ts

Closes #184
As far as I can tell, you still need to acquire the arcane adatper using hacky ways, as I don't see any way to buy them with plat.

feat: implement arcane adapters

---

src/controllers/api/upgradesController.ts
src/models/inventoryModels/inventoryModel.ts
src/types/inventoryTypes/SuitTypes.ts
src/types/inventoryTypes/inventoryTypes.ts
src/types/inventoryTypes/weaponTypes.ts

feat: implement purchasing of additional mod & customization slots

---

package-lock.json
package.json
src/pathman.ts

fix: errors with `npm run build && npm run start`

---

src/services/inventoryService.ts
src/services/purchaseService.ts

feat: implement purchasing of blueprints & gear items

---

src/controllers/custom/getItemListsController.ts
static/webui/index.html
static/webui/script.js

This can be used to get items such as:
- Resources required for blueprints
- Simulacrum access key & rooms
- Archon Shards

feat(webui): add "Add Items" to acquire various items

---

src/controllers/dynamic/worldStateController.ts
static/fixed_responses/worldState.json

- BuildLabel is automatically populated from config
- News is replaced
- Removed contemporary stuff (thermia fractures, flash sales)
- "Expiry" fields extended comfortably into the future (closes #197)
A lot of stuff that could still be done in this area, but you gotta start somewhere.

feat: initial steps towards an independent worldState

---

static/fixed_responses/allMissions.json

These are needed to unlock arbitrations

feat: update allMissions.json

---

src/controllers/api/getDailyDealStockLevelsController.ts
src/routes/api.ts
static/fixed_responses/worldState.json

Clem just came in with a new shipment of supplies or something

feat: restock darvo

---

src/controllers/api/updateChallengeProgressController.ts
src/services/inventoryService.ts

feat: handle updateChallengeProgress

---

.github/workflows/build.yml
.gitignore
static/data/buildConfig.json

I think it makes more sense for this file to be distributed with the cache file

improve: remove buildConfig.json from git

---

src/models/inventoryModels/inventoryModel.ts

Add XP for SpaceSuits

---

src/controllers/api/sellController.ts
src/models/inventoryModels/inventoryModel.ts
src/services/inventoryService.ts

feat: implement selling/dissolving of mods

---

src/controllers/custom/addItemController.ts
src/helpers/customHelpers/addItemHelpers.ts
static/webui/script.js

improve: authenticate addItem requests

---

src/index.ts
src/services/mongoService.ts

- Print "Starting up..." ASAP so the user knows we're doing something
- Fixed inconsistencies in casing & terminology

improve: logging during startup sequence

---

src/controllers/api/upgradesController.ts

feat: handle installation of aura & stance formas

---

package-lock.json
package.json
src/controllers/custom/getItemListsController.ts
src/services/itemDataService.ts

An initial step towards moving away from warframe-items.
Closes #256

fix(webui): not listing melee arcanes

---

package-lock.json
package.json

chore: update warframe-items so Tenet Glaxion etc are known

---

src/controllers/api/upgradesController.ts
src/models/inventoryModels/inventoryModel.ts
src/types/requestTypes.ts

feat: implement polarity swapping

---

package-lock.json
package.json
src/controllers/custom/getItemListsController.ts
src/helpers/customHelpers/addItemHelpers.ts
src/services/itemDataService.ts
static/webui/script.js

fix: being unable to add Grimoire

---

config.json.example
src/controllers/api/getShipController.ts
src/services/configService.ts

Fixed a typo in unlockAllShipFeatures in config.json and other needed files.

Fixed Typo in config.json

---

src/controllers/api/claimCompletedRecipeController.ts
src/controllers/api/inventorySlotsController.ts
src/services/inventoryService.ts
src/services/purchaseService.ts
src/types/inventoryTypes/inventoryTypes.ts
src/types/purchaseTypes.ts

feat: rushing recipes, refactor: addItem

---

src/controllers/custom/getConfigDataController.ts
src/controllers/custom/updateConfigDataController.ts
src/services/configService.ts
static/webui/index.html

As a side effect, hot-reloading the config is now a feature of SNS, so it's not exclusive to dev mode.
Closes #296

fix: config change on WebUI causing hot reload in dev mode

---

src/services/inventoryService.ts

Previously, you could already "purchase" most of them, but because they were added to MiscItems instead of ShipDecorations, they weren't actually usable.
Closes #207

feat: purchase shop decorations

---

src/models/personalRoomsModel.ts
src/services/shipCustomizationsService.ts
src/types/shipTypes.ts

fix: move ship decorations

---

package-lock.json
package.json
src/services/purchaseService.ts

feat: implement purchasing of bundles

---

src/services/saveLoadoutService.ts

improve: save loadouts for all item types

---

src/controllers/api/nameWeaponController.ts
src/controllers/api/upgradesController.ts
src/routes/api.ts
src/types/inventoryTypes/inventoryTypes.ts
static/webui/script.js
static/webui/style.css

feat: custom item names

---

src/controllers/api/claimCompletedRecipeController.ts
src/services/inventoryService.ts
src/services/itemDataService.ts
src/services/recipeService.ts

fix: not being able to purchase or craft some recipes

---

src/controllers/api/claimCompletedRecipeController.ts
src/services/itemDataService.ts
src/services/recipeService.ts

- Resources and credits are deducted when starting a recipe
- Resources and credits are refunded when cancelling the recipe
- The recipe is consumed if it is not reusable
Closes #251

feat: handle costs of recipes

---

src/controllers/api/sellController.ts

feat: implement selling of recipes

---

src/controllers/api/stepSequencersController.ts
src/routes/api.ts
src/types/inventoryTypes/inventoryTypes.ts

feat: implement stepSequencers.php

---

src/models/inventoryModels/inventoryModel.ts
src/services/inventoryService.ts
src/types/inventoryTypes/inventoryTypes.ts

feat: handle purchasing of archwing, archgun, & archmelee

---

src/controllers/api/getVendorInfoController.ts
src/routes/api.ts
static/fixed_responses/getVendorInfo.json

fix: not being able to talk to Nakak in Cetus

---

static/fixed_responses/modularWeaponSale.json

I think only the Expiry needed to be in a point that's not in the past, but I also fetched fresh data for it yesterday just in case, and it seems it still works today.

fix: view "Today's Special"

---

src/controllers/api/focusController.ts

feat: implement unbinding of focus upgrades

---

src/controllers/api/missionInventoryUpdateController.ts
src/services/missionInventoryUpdateService.ts
src/types/requestTypes.ts

fix: endo pickups

---

src/controllers/api/upgradesController.ts
src/types/inventoryTypes/commonInventoryTypes.ts
src/types/inventoryTypes/inventoryTypes.ts
src/types/requestTypes.ts

feat: gravimag installation

---

src/services/missionInventoryUpdateService.ts
src/types/requestTypes.ts

fix: spy mission rewards

---

package-lock.json
package.json
src/controllers/custom/getItemListsController.ts
src/services/itemDataService.ts

cleanup: yeet warframe-items

---

package-lock.json
package.json
src/services/missionInventoryUpdateService.ts

feat: rewards for enemy caches & rathuum

---

static/webui/index.html

Put the item lists below the buttons to add items, because otherwise adding large quantities of things gets increasingly more annoying with the constant scroll down.

improve(webui): Reorder Item List and Add Item Button

---

src/controllers/api/inventoryController.ts
src/types/inventoryTypes/inventoryTypes.ts

fix: foundry keeps refreshing, thinking argon crystals are expired

---

src/services/inventoryService.ts
static/webui/index.html

improve: purchasing of animation sets, colour plattes, etc.

---

package-lock.json
package.json
src/services/purchaseService.ts

improve: handle purchase quantity of gear items

---

.eslintrc
src/controllers/api/addFriendImageController.ts
src/controllers/api/claimCompletedRecipeController.ts
src/controllers/api/createGuildController.ts
src/controllers/api/evolveWeaponController.ts
src/controllers/api/findSessionsController.ts
src/controllers/api/focusController.ts
src/controllers/api/genericUpdateController.ts
src/controllers/api/infestedFoundryController.ts
src/controllers/api/joinSessionController.ts
src/controllers/api/modularWeaponCraftingController.ts
src/controllers/api/nameWeaponController.ts
src/controllers/api/sellController.ts
src/controllers/api/setWeaponSkillTreeController.ts
src/controllers/api/startDojoRecipeController.ts
src/controllers/api/startRecipeController.ts
src/controllers/api/stepSequencersController.ts
src/controllers/api/syndicateSacrificeController.ts
src/controllers/api/trainingResultController.ts
src/controllers/api/updateChallengeProgressController.ts
src/controllers/api/updateSessionController.ts
src/controllers/api/upgradesController.ts
src/controllers/custom/updateConfigDataController.ts

fix: Convert all Body to String Before Use

---

src/models/inventoryModels/inventoryModel.ts

fix: affiliationsSchema not matching IAffiliation

---

src/models/inventoryModels/inventoryModel.ts
src/types/inventoryTypes/inventoryTypes.ts
static/fixed_responses/new_inventory.json
static/fixed_responses/postTutorialInventory.json

add missing varible found in #401

improve: add DailyAffiliationCavia

---

src/models/inventoryModels/loadoutModel.ts
src/types/inventoryTypes/inventoryTypes.ts

improve: loadout config save FocusSchool

---

src/controllers/api/gildWeaponController.ts
src/routes/api.ts
src/types/inventoryTypes/commonInventoryTypes.ts

feat: gilded weapons

---

static/webui/style.css

some users might otherwise be unable to use certain actions

fix(webui): add scrollbar to cards if needed

---

src/services/inventoryService.ts
src/types/inventoryTypes/inventoryTypes.ts
src/types/requestTypes.ts

feat: track LastRegionPlayed

---

package-lock.json
package.json

chore: update warframe-public-export-plus

---

src/services/inventoryService.ts

feat: handle acquisition of upgrades (mods & arcanes)

---

src/controllers/api/focusController.ts
src/controllers/api/modularWeaponCraftingController.ts
src/controllers/custom/addItemController.ts
src/models/inventoryModels/inventoryModel.ts
src/services/inventoryService.ts
src/types/inventoryTypes/inventoryTypes.ts

feat: moa pet assembly

---

src/services/missionInventoryUpdateService.ts

fix: not getting cache rewards due to early bail

---

src/controllers/api/modularWeaponCraftingController.ts

fix: hound building

---

src/controllers/api/upgradesController.ts

feat: installation of amp arcane adapter

---

src/controllers/api/tauntHistoryController.ts
src/models/inventoryModels/inventoryModel.ts
src/routes/api.ts
src/types/inventoryTypes/inventoryTypes.ts

This endpoint only seems used for Maroo, so this is probably the most useless thing ever, but then again, [insert joke here] exists.
Closes #418

feat: implement tauntHistory.php

---

package-lock.json
package.json
src/services/inventoryService.ts
src/services/missionInventoryUpdateService.ts
src/services/purchaseService.ts
src/services/rngService.ts

feat: handle acquisition of booster packs

---

src/services/saveLoadoutService.ts
src/types/saveLoadoutTypes.ts

feat: save EquippedEmotes

---

src/controllers/api/projectionManagerController.ts
src/routes/api.ts

feat: void relic refinement

---

src/services/inventoryService.ts
src/types/requestTypes.ts

fix: ayatan statue saving

---

src/controllers/api/genericUpdateController.ts
src/routes/api.ts

fix: add /api/updateNodeIntros.php as an alias for /api/genericUpdate.php

---

src/controllers/api/arcaneCommonController.ts
src/routes/api.ts

feat: implement upgrading & downgrading arcanes

---

package-lock.json
package.json

chore: update PE+ to 0.5.1

---

src/controllers/custom/tunablesController.ts
src/routes/custom.ts

This has been in the DLL for ages without any real documentation, so this should serve as the documentation now.

feat: add tunables endpoint

---

src/services/missionInventoryUpdateService.ts

chore: handle resource being rolled as mission reward

---

src/controllers/api/focusController.ts

Should work correctly, hopefully. Do scream at me if I did a big dumbo. Fixes #539.

Implement installation of Focus Lenses

---

src/controllers/api/inventoryController.ts

Gives the skins IDs so the game doesn't give empty customization slots. Fixes #548

fix: Apply Look not working with Unlock All Skins turned on

---

src/controllers/api/inventoryController.ts

fix: being unable to visit Palladino in Iron Wake despite completeAllQuests

---

src/controllers/api/getVendorInfoController.ts
static/fixed_responses/getVendorInfo/DeimosEntratiFragmentVendorProductsManifest.json
static/fixed_responses/getVendorInfo/DeimosFishmongerVendorManifest.json
static/fixed_responses/getVendorInfo/DeimosHivemindCommisionsManifestFishmonger.json
static/fixed_responses/getVendorInfo/DeimosHivemindCommisionsManifestPetVendor.json
static/fixed_responses/getVendorInfo/DeimosHivemindCommisionsManifestProspector.json
static/fixed_responses/getVendorInfo/DeimosHivemindCommisionsManifestTokenVendor.json
static/fixed_responses/getVendorInfo/DeimosHivemindCommisionsManifestWeaponsmith.json
static/fixed_responses/getVendorInfo/DeimosHivemindTokenVendorManifest.json
static/fixed_responses/getVendorInfo/DeimosPetVendorManifest.json
static/fixed_responses/getVendorInfo/DeimosProspectorVendorManifest.json
static/fixed_responses/getVendorInfo/DuviriAcrithisVendorManifest.json
static/fixed_responses/getVendorInfo/EntratiLabsEntratiLabVendorManifest.json
static/fixed_responses/getVendorInfo/EntratiLabsEntratiLabsCommisionsManifest.json
static/fixed_responses/getVendorInfo/HubsIronwakeDondaVendorManifest.json
static/fixed_responses/getVendorInfo/HubsRailjackCrewMemberVendorManifest.json
static/fixed_responses/getVendorInfo/OstronFishmongerVendorManifest.json
static/fixed_responses/getVendorInfo/OstronPetVendorManifest.json
static/fixed_responses/getVendorInfo/OstronProspectorVendorManifest.json
static/fixed_responses/getVendorInfo/SolarisDebtTokenVendorManifest.json
static/fixed_responses/getVendorInfo/SolarisDebtTokenVendorRepossessionsManifest.json
static/fixed_responses/getVendorInfo/SolarisFishmongerVendorManifest.json
static/fixed_responses/getVendorInfo/SolarisProspectorVendorManifest.json

If there's any missing, please do mention it, but I think I got them all. Fixes #562. Fixes #560.

fix: missing vendor infos

---

src/controllers/api/getVendorInfoController.ts
static/fixed_responses/getVendorInfo/HubsPerrinSequenceWeaponVendorManifest.json

Fixes #567. If anyone can find any missing shops, please tell me.

improve: Add Ergo Blast's Tenet Weapon shop

---

package-lock.json
package.json

chore: update PE+ to 0.5.5

---

src/services/inventoryService.ts

fix: purchasing of augment mods

---

src/services/inventoryService.ts

fix: unable to buy fish bait

---

package-lock.json
package.json
src/controllers/api/infestedFoundryController.ts
src/models/inventoryModels/inventoryModel.ts
src/types/inventoryTypes/inventoryTypes.ts

More progress on #288. Currently, Helminth never gets tired of resources; this may be implemented later.

feat: implement feeding of helminth

---

src/controllers/api/getShipController.ts
src/controllers/api/shipDecorationsController.ts
src/models/personalRoomsModel.ts
src/services/shipCustomizationsService.ts
src/types/personalRoomsTypes.ts
src/types/shipTypes.ts

feat: decorating the backroom

---

src/services/shipCustomizationsService.ts
src/types/shipTypes.ts

fix: don't default scale of ship decoration to 1

---

package-lock.json
package.json
src/services/purchaseService.ts
src/types/purchaseTypes.ts

fix: purchasing an arcane pack does not consume vosfor

---

src/controllers/api/endlessXpController.ts
src/models/inventoryModels/inventoryModel.ts
src/routes/api.ts
src/types/inventoryTypes/inventoryTypes.ts

feat: basic implementation of endlessXp.php we can play The Circuit

---

src/controllers/custom/getItemListsController.ts
src/services/itemDataService.ts
static/webui/index.html
static/webui/script.js

 feat(webui): language selector

---

src/controllers/api/getVendorInfoController.ts
src/services/purchaseService.ts
src/services/serversideVendorsService.ts

feat: apply QuantityMultiplier for server-side vendor offers

---

src/models/inventoryModels/inventoryModel.ts
src/services/purchaseService.ts
src/types/inventoryTypes/inventoryTypes.ts
src/types/purchaseTypes.ts

feat: implement aya costs for varzia offers

---

package-lock.json
package.json
src/services/purchaseService.ts
src/types/purchaseTypes.ts

feat: subtract standing for syndicate purchases

---

src/controllers/custom/deleteAccountController.ts
src/routes/custom.ts
static/webui/index.html
static/webui/script.js

feat(webui): delete account

---

src/controllers/custom/renameAccountController.ts
src/routes/custom.ts
static/webui/index.html
static/webui/script.js

feat(webui): rename account

---

package-lock.json
package.json
src/controllers/custom/getItemListsController.ts
src/services/itemDataService.ts

feat(webui): ability to add recipes via "add items"

---

config.json.example
src/controllers/api/loginController.ts
src/controllers/custom/createAccountController.ts
src/controllers/custom/getConfigDataController.ts
src/controllers/custom/renameAccountController.ts
src/controllers/custom/updateConfigDataController.ts
src/models/loginModel.ts
src/services/configService.ts
src/services/loginService.ts
static/webui/index.html
static/webui/script.js

feat: add administrators, require administrator perms to change server config in webui

---

src/services/inventoryService.ts

fix: give respective weapons & mods when acquiring sentinel

---

src/models/inventoryModels/inventoryModel.ts
src/models/inventoryModels/loadoutModel.ts
src/services/inventoryService.ts
src/types/inventoryTypes/inventoryTypes.ts

fix: acquisition of railjack

---

src/app.ts
src/index.ts
src/services/mongoService.ts

improve: tell user that the WebUI is available

---

package-lock.json
package.json
src/controllers/api/getGuildDojoController.ts
src/controllers/api/queueDojoComponentDestructionController.ts
src/controllers/api/startDojoRecipeController.ts
src/models/guildModel.ts
src/types/guildTypes.ts

feat: dojo room energy & capacity costs & gains

---

src/controllers/api/sellController.ts
src/types/sellTypes.ts

fix: can't dissolve arcanes

---

src/controllers/api/sellController.ts
src/types/sellTypes.ts

fix: selling consumable/gear items

---

static/fixed_responses/worldState.json

fix: no hex bounties available

---

package-lock.json
package.json
src/services/inventoryService.ts
src/services/purchaseService.ts
src/types/syndicateTypes.ts

feat: syndicate initiation

---

src/services/inventoryService.ts
src/services/purchaseService.ts
src/types/purchaseTypes.ts

fix: booster packs not showing what items were gained after purchase

---

src/controllers/custom/getItemListsController.ts
static/webui/script.js

improve: for "make rank 30", also make respective exalted items rank 30

---

config.json.example
package-lock.json
package.json
src/controllers/api/inventoryController.ts
src/services/configService.ts
static/webui/index.html
static/webui/script.js

feat: unlock all captura scenes

---

src/controllers/api/setShipFavouriteLoadoutController.ts
src/routes/api.ts

feat: implement setShipFavouriteLoadout.php

---

src/controllers/api/sellController.ts

It would throw the "Unknown SellCurrency" error when trying to sell items for ducats in the trading kiosk because it wasnt being handled properly.

fix: error when attempting to sell items for ducats

---

src/controllers/api/upgradesController.ts
src/services/itemDataService.ts

feat: infusing abilities

---

package-lock.json
package.json
src/controllers/api/fishmongerController.ts

feat: trade fish for standing

---

src/controllers/api/infestedFoundryController.ts
src/controllers/api/inventoryController.ts
src/models/inventoryModels/inventoryModel.ts
src/types/inventoryTypes/inventoryTypes.ts

feat: subsuming warframes

---

src/controllers/api/evolveWeaponController.ts

feat: remove incarnon

---

src/controllers/api/createGuildController.ts
src/controllers/api/guildTechController.ts
src/models/guildModel.ts
src/models/inventoryModels/inventoryModel.ts
src/services/guildService.ts
src/types/guildTypes.ts
src/types/inventoryTypes/inventoryTypes.ts

feat: dojo research

---

src/controllers/api/claimCompletedRecipeController.ts
src/controllers/api/focusController.ts
src/controllers/api/inventorySlotsController.ts
src/controllers/api/modularWeaponCraftingController.ts
src/controllers/custom/addItemController.ts
src/services/inventoryService.ts
src/services/purchaseService.ts

purchase 50 arcane packs - before: 2715.070 ms
purchase 50 arcane packs - after: 183.988 ms

chore: do addItem on inventory document, not accountId

---

src/controllers/api/guildTechController.ts

feat: replicate dojo research

---

package-lock.json
package.json
src/controllers/custom/getItemListsController.ts

fix(webui): diambiguate fish names

---

src/controllers/api/inventoryController.ts

feat: correctly scale standing and focus limits by mastery rank

---

src/controllers/api/infestedFoundryController.ts
src/models/inventoryModels/inventoryModel.ts
src/types/inventoryTypes/commonInventoryTypes.ts

feat: invigorations

---

src/controllers/api/infestedFoundryController.ts
src/controllers/api/upgradesController.ts
src/services/inventoryService.ts
src/types/purchaseTypes.ts

feat: all server-side metamorphosis levels

---

src/controllers/api/infestedFoundryController.ts
src/models/inventoryModels/inventoryModel.ts
src/types/inventoryTypes/inventoryTypes.ts

feat: helminth losing apetite

---

src/controllers/api/infestedFoundryController.ts

Maybe actually the last of #288. Some points where I'm not sure I got it 100% right/faithful with the 'OG', but oh well.

feat: sentient apetite

---

src/controllers/api/infestedFoundryController.ts

Fixup for #724. Should finally complete #288.

fix: removing an archon shard doesn't refund it

---

src/controllers/api/claimCompletedRecipeController.ts
src/controllers/api/startRecipeController.ts
src/models/inventoryModels/inventoryModel.ts
src/types/inventoryTypes/inventoryTypes.ts

feat: spectre loadouts

---

src/controllers/api/syndicateSacrificeController.ts

fix: remove syndicate sacrifices from inventory

---

src/controllers/api/getVoidProjectionRewardsController.ts
src/routes/api.ts
src/services/rngService.ts

A partial solution for #415 without touching missionInventoryUpdate.

feat: opening relics in endless missions

---

package-lock.json
package.json
src/controllers/api/activateRandomModController.ts
src/routes/api.ts
src/services/rngService.ts

feat: activate riven mod (get a random challenge)

---

src/controllers/api/playerSkillsController.ts
src/models/inventoryModels/inventoryModel.ts
src/routes/api.ts
src/types/inventoryTypes/inventoryTypes.ts

feat: leveling up intrinsics

---

config.json.example
src/controllers/api/inventoryController.ts
src/services/configService.ts
src/services/inventoryService.ts
src/services/purchaseService.ts
static/webui/index.html
static/webui/script.js

feat: infiniteEndo & infiniteRegalAya

---

src/services/serversideVendorsService.ts
static/fixed_responses/getVendorInfo/RadioLegionIntermission10VendorManifest.json

fixes #742
added static shop for nora's nightwave offerings

added nora night vendor data (#742)

---

src/controllers/api/syndicateStandingBonusController.ts

fix: limit standing gain from medallions for title's max

---

config.json.example
src/controllers/api/inventoryController.ts
src/services/configService.ts
static/webui/index.html
static/webui/script.js

feat: add potatoes, exilus, & arcanes everywhere cheats

---

src/controllers/dynamic/worldStateController.ts

The recent calendar fix made this unaligned with the official cycle, also for this week some of the weapon names were incorrect.

fix: incarnon options cycle

---

src/services/serversideVendorsService.ts
static/fixed_responses/getVendorInfo/RadioLegionIntermission11VendorManifest.json
static/fixed_responses/worldState/worldState.json

Changed worldState to use nora's mix volume 7

chore: update nightwave to nora's mix vol. 7

---

src/controllers/api/syndicateStandingBonusController.ts
src/services/inventoryService.ts
src/types/inventoryTypes/inventoryTypes.ts

feat: apply & track daily standing limit when trading in medallions

---

config.json.example
src/controllers/api/inventoryController.ts
src/controllers/api/syndicateStandingBonusController.ts
src/services/configService.ts
src/services/inventoryService.ts
static/webui/index.html

feat: noDailyStandingLimits cheat

---

src/controllers/api/fishmongerController.ts
src/controllers/api/syndicateStandingBonusController.ts
src/helpers/syndicateStandingHelper.ts

fix: handle standing limits in fishmongerController

---

src/controllers/api/syndicateSacrificeController.ts
src/services/purchaseService.ts

fix: track FreeFavorsEarned & FreeFavorsUsed

---

src/services/purchaseService.ts

fix: not consuming ItemPrices from server-side vendor

---

src/controllers/api/clearDialogueHistoryController.ts
src/controllers/api/saveDialogueController.ts
src/models/inventoryModels/inventoryModel.ts
src/routes/api.ts
src/types/inventoryTypes/inventoryTypes.ts

feat: Kinematic Instant Messaging

---

src/controllers/custom/addItemsController.ts

fix: add slots when adding items via WebUI

---

src/services/loginService.ts

we only need to check for existence, not get any data back

chore: optimise getAccountIdForRequest

---

src/controllers/api/creditsController.ts
src/services/inventoryService.ts

chore: optimise creditsController

---

src/controllers/stats/viewController.ts
src/services/inventoryService.ts
static/fixed_responses/allScans.json

~30ms to ~6ms (with unlockAllScans)

chore: optimise stats/view.php

---

src/controllers/api/syndicateStandingBonusController.ts

fix: classical syndicate medallions don't use daily limit

---

src/controllers/api/sellController.ts
src/controllers/custom/addItemsController.ts
src/controllers/custom/getItemListsController.ts
src/helpers/purchaseHelpers.ts
src/services/inventoryService.ts
static/webui/index.html
static/webui/script.js

Closes #811 Closes #809 Closes #620 Closes #440

feat(webui): more equipment

---

static/webui/index.html
static/webui/script.js

feat(webui): mod count

---

src/controllers/custom/getItemListsController.ts
static/webui/script.js

fix(webui): properly handle unique level caps

---

src/services/importService.ts

false/0 would not be imported, but should be as long as they are present.

fix: slight logic error in importService

---

src/models/inventoryModels/inventoryModel.ts
src/services/importService.ts
src/types/inventoryTypes/inventoryTypes.ts

fix: rectify CrewMembers import & typings

---

package-lock.json
src/controllers/api/giveKeyChainTriggeredItemsController.ts
src/controllers/api/inventoryController.ts
src/controllers/api/inventorySlotsController.ts
src/controllers/api/missionInventoryUpdateController.ts
src/controllers/api/unlockShipFeatureController.ts
src/controllers/api/updateQuestController.ts
src/models/inventoryModels/inventoryModel.ts
src/models/personalRoomsModel.ts
src/routes/api.ts
src/services/inventoryService.ts
src/services/itemDataService.ts
src/services/loginService.ts
src/services/missionInventoryUpdateService.ts
src/services/personalRoomsService.ts
src/services/questService.ts
src/types/inventoryTypes/inventoryTypes.ts
src/types/missionTypes.ts
src/types/requestTypes.ts
static/fixed_responses/questCompletionRewards.json

Not fully functional yet, quests won't complete.
Quests 2 will complete quests and will be pushed in a few days.

feat: Quests1

---

src/controllers/custom/addXpController.ts
src/routes/custom.ts
static/webui/script.js

fix(webui): max rank

---

src/controllers/api/missionInventoryUpdateController.ts
src/services/missionInventoryUpdateService.ts
src/utils/ts-utils.ts

also creates ts-utils in utils

fix: adjust mission update controller

---

src/controllers/api/inventoryController.ts
src/controllers/api/missionInventoryUpdateController.ts

fix: provide LoadOutPresets & Ships in missionInventoryUpdate response

---

src/models/inventoryModels/inventoryModel.ts
src/services/importService.ts
src/services/missionInventoryUpdateService.ts
src/services/saveLoadoutService.ts
src/types/inventoryTypes/commonInventoryTypes.ts
src/types/inventoryTypes/inventoryTypes.ts
src/types/requestTypes.ts
src/types/saveLoadoutTypes.ts

feat: more supported equipment types

---

src/services/inventoryService.ts
src/services/missionInventoryUpdateService.ts
src/types/requestTypes.ts

feat: earn focus xp with a lens

---

src/models/inventoryModels/inventoryModel.ts
src/services/inventoryService.ts
src/types/inventoryTypes/inventoryTypes.ts

fix: correctly add kubrow eggs to inventory

---

src/controllers/api/startLibraryPersonalTargetController.ts
src/models/inventoryModels/inventoryModel.ts
src/routes/api.ts
src/types/inventoryTypes/inventoryTypes.ts

feat: startLibraryPersonalTarget

---

src/services/missionInventoryUpdateService.ts
src/types/requestTypes.ts

feat: earning intrinsics
